import type { Drama, Category } from "@/types";

// Mock data for development — 50 short dramas
export const mockDramas: Drama[] = [
  {
    _id: "1",
    title: "The CEO's Secret Contract",
    cover: "https://picsum.photos/seed/drama1/400/600",
    description: "When a struggling artist accidentally signs a marriage contract with the city's most powerful CEO, she finds herself trapped in a world of luxury, lies, and unexpected passion.",
    categories: ["Romance","CEO","Drama"],
    actors: ["Emma Stone","James Chen"],
    rating: 8.7,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 80,
    isFeatured: true,
    createdAt: "2024-01-01",
  },
  {
    _id: "2",
    title: "Revenge of the Princess",
    cover: "https://picsum.photos/seed/drama2/400/600",
    description: "Betrayed by her own family, a fallen princess rises from the ashes to reclaim her throne and destroy those who wronged her.",
    categories: ["Revenge","Historical","Drama"],
    actors: ["Alice Wang","Bob Chen"],
    rating: 9.1,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 60,
    isFeatured: true,
    createdAt: "2024-02-02",
  },
  {
    _id: "3",
    title: "Sweet Love in Office",
    cover: "https://picsum.photos/seed/drama3/400/600",
    description: "Two rival executives discover unexpected chemistry when they're forced to share an office for a month.",
    categories: ["Romance","Comedy"],
    actors: ["Carol Zhang","David Li"],
    rating: 8.3,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 45,
    createdAt: "2024-03-03",
  },
  {
    _id: "4",
    title: "Mysterious Doctor",
    cover: "https://picsum.photos/seed/drama4/400/600",
    description: "A brilliant surgeon with a hidden past uncovers a conspiracy that threatens everyone she loves.",
    categories: ["Mystery","Suspense"],
    actors: ["Eve Liu","Frank Wu"],
    rating: 8.6,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 55,
    createdAt: "2024-04-04",
  },
  {
    _id: "5",
    title: "Powerful CEO",
    cover: "https://picsum.photos/seed/drama5/400/600",
    description: "From the streets to the boardroom — one man's ruthless rise to power and the woman who changes everything.",
    categories: ["CEO","Drama"],
    actors: ["Grace Yang","Henry Zhou"],
    rating: 8.4,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 70,
    createdAt: "2024-05-05",
  },
  {
    _id: "6",
    title: "Love in the City",
    cover: "https://picsum.photos/seed/drama6/400/600",
    description: "Three best friends navigate love, heartbreak, and ambition in the city that never sleeps.",
    categories: ["Romance","Urban"],
    actors: ["Ivy Chen","Jack Ma"],
    rating: 8.2,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 40,
    createdAt: "2024-06-06",
  },
  {
    _id: "7",
    title: "Wolf Moon Rising",
    cover: "https://picsum.photos/seed/drama7/400/600",
    description: "A forbidden love between a werewolf prince and a human girl threatens to ignite an ancient war between their worlds.",
    categories: ["Werewolf","Fantasy","Romance"],
    actors: ["Luna Park","Derek Moon"],
    rating: 9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 90,
    isFeatured: true,
    createdAt: "2024-07-07",
  },
  {
    _id: "8",
    title: "The Billionaire's Bride",
    cover: "https://picsum.photos/seed/drama8/400/600",
    description: "A contract marriage between a cold billionaire and a spirited waitress turns into the love story of the century.",
    categories: ["Romance","CEO"],
    actors: ["Sophie Lin","Marcus Chen"],
    rating: 8.8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 65,
    createdAt: "2024-08-08",
  },
  {
    _id: "9",
    title: "Dark Throne",
    cover: "https://picsum.photos/seed/drama9/400/600",
    description: "In a kingdom where magic is forbidden, a young sorceress must reclaim the throne stolen from her bloodline.",
    categories: ["Fantasy","Revenge"],
    actors: ["Aria Storm","Kai Blackwood"],
    rating: 9.2,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 100,
    isFeatured: true,
    createdAt: "2024-09-09",
  },
  {
    _id: "10",
    title: "Undercover Hearts",
    cover: "https://picsum.photos/seed/drama10/400/600",
    description: "An undercover agent falls for her target — but when her cover is blown, she must choose between duty and love.",
    categories: ["Suspense","Romance"],
    actors: ["Mia Zhang","Leo Wang"],
    rating: 8.5,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 50,
    createdAt: "2024-10-10",
  },
  {
    _id: "11",
    title: "Eternal Flame",
    cover: "https://picsum.photos/seed/drama11/400/600",
    description: "A love that transcends time itself — two souls connected across centuries finally meet in the modern world.",
    categories: ["Fantasy","Romance"],
    actors: ["Stella Kim","Ryan Park"],
    rating: 8.9,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 75,
    createdAt: "2024-11-11",
  },
  {
    _id: "12",
    title: "Vengeance is Mine",
    cover: "https://picsum.photos/seed/drama12/400/600",
    description: "She lost everything — her family, her fortune, her name. Now she's back, and no one is safe.",
    categories: ["Revenge","Drama"],
    actors: ["Victoria Zhao","Nathan Li"],
    rating: 9.3,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 85,
    isFeatured: true,
    createdAt: "2024-12-12",
  },
  {
    _id: "13",
    title: "Forbidden Alpha",
    cover: "https://picsum.photos/seed/drama13/400/600",
    description: "The alpha of the strongest pack falls for a rogue wolf — defying every law of their kind.",
    categories: ["Werewolf","Romance"],
    actors: ["Amber Fox","Tyler Reed"],
    rating: 8.7,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 72,
    createdAt: "2024-01-13",
  },
  {
    _id: "14",
    title: "My Husband is a Ghost",
    cover: "https://picsum.photos/seed/drama14/400/600",
    description: "After a freak accident, a woman discovers her new husband is actually a 200-year-old ghost bound to their apartment.",
    categories: ["Fantasy","Comedy","Romance"],
    actors: ["Nina Hart","Sam Cross"],
    rating: 8.1,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 48,
    createdAt: "2024-02-14",
  },
  {
    _id: "15",
    title: "The Dragon King's Mate",
    cover: "https://picsum.photos/seed/drama15/400/600",
    description: "In a world where dragons rule, a human girl is chosen as the mate of the most feared Dragon King.",
    categories: ["Fantasy","Romance"],
    actors: ["Jade Wu","Ethan Lam"],
    rating: 9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 88,
    createdAt: "2024-03-15",
  },
  {
    _id: "16",
    title: "Betrayed by Blood",
    cover: "https://picsum.photos/seed/drama16/400/600",
    description: "When she discovers her twin sister stole her identity and her life, she wages a war that will destroy them both.",
    categories: ["Revenge","Suspense"],
    actors: ["Chloe Tan","Max Rivera"],
    rating: 8.8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 62,
    createdAt: "2024-04-16",
  },
  {
    _id: "17",
    title: "CEO's Hidden Heir",
    cover: "https://picsum.photos/seed/drama17/400/600",
    description: "Five years after a one-night stand, she returns to the city — with his child he never knew existed.",
    categories: ["CEO","Romance","Drama"],
    actors: ["Lily Fang","Owen Blake"],
    rating: 8.5,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 56,
    createdAt: "2024-05-17",
  },
  {
    _id: "18",
    title: "Moonlit Wolves",
    cover: "https://picsum.photos/seed/drama18/400/600",
    description: "Two rival wolf packs must unite against a common enemy, but the alpha's daughter falls for the enemy's son.",
    categories: ["Werewolf","Fantasy"],
    actors: ["Ruby Moon","Zane Wolf"],
    rating: 8.6,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 68,
    createdAt: "2024-06-18",
  },
  {
    _id: "19",
    title: "The Perfect Revenge",
    cover: "https://picsum.photos/seed/drama19/400/600",
    description: "She married her enemy's son to destroy his empire from within — but she didn't plan on falling in love.",
    categories: ["Revenge","Romance"],
    actors: ["Serena Voss","Dante Cruz"],
    rating: 9.1,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 78,
    createdAt: "2024-07-19",
  },
  {
    _id: "20",
    title: "Trapped with the CEO",
    cover: "https://picsum.photos/seed/drama20/400/600",
    description: "An elevator malfunction traps a junior employee with the company's intimidating CEO for 12 hours.",
    categories: ["CEO","Romance"],
    actors: ["Tessa Lin","Jace Park"],
    rating: 8.3,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 52,
    createdAt: "2024-08-20",
  },
  {
    _id: "21",
    title: "Shadow Assassin",
    cover: "https://picsum.photos/seed/drama21/400/600",
    description: "The world's deadliest assassin takes on one final mission — but her target makes her question everything.",
    categories: ["Suspense","Romance"],
    actors: ["Kira Blade","Axel Storm"],
    rating: 8.7,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 64,
    createdAt: "2024-09-21",
  },
  {
    _id: "22",
    title: "Rebirth of the Queen",
    cover: "https://picsum.photos/seed/drama22/400/600",
    description: "After being murdered by her husband, she's reborn 10 years in the past with all her memories — and a plan.",
    categories: ["Revenge","Fantasy"],
    actors: ["Nora Quinn","Rhys Dark"],
    rating: 9.4,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 95,
    isFeatured: true,
    createdAt: "2024-10-22",
  },
  {
    _id: "23",
    title: "Love After Midnight",
    cover: "https://picsum.photos/seed/drama23/400/600",
    description: "A night-shift nurse and a mysterious patient share stolen moments that change both their lives forever.",
    categories: ["Romance","Urban"],
    actors: ["Faye Chen","Luke West"],
    rating: 8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 38,
    createdAt: "2024-11-23",
  },
  {
    _id: "24",
    title: "The Alpha's Rejected Mate",
    cover: "https://picsum.photos/seed/drama24/400/600",
    description: "Rejected by her fated mate on her 18th birthday, she transforms into the most powerful she-wolf in history.",
    categories: ["Werewolf","Romance"],
    actors: ["Zara Night","Cole Hunter"],
    rating: 8.9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 82,
    createdAt: "2024-12-24",
  },
  {
    _id: "25",
    title: "Billionaire's Secret Baby",
    cover: "https://picsum.photos/seed/drama25/400/600",
    description: "She hid his child for three years. Now he's found them — and he wants everything.",
    categories: ["CEO","Romance","Drama"],
    actors: ["Mila Rose","Dean Frost"],
    rating: 8.4,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 58,
    createdAt: "2024-01-25",
  },
  {
    _id: "26",
    title: "Witch's Heart",
    cover: "https://picsum.photos/seed/drama26/400/600",
    description: "The last witch in a world that hunts her kind falls for the hunter sent to capture her.",
    categories: ["Fantasy","Romance"],
    actors: ["Iris Flame","Kai Shadow"],
    rating: 8.6,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 66,
    createdAt: "2024-02-26",
  },
  {
    _id: "27",
    title: "Deadly Vows",
    cover: "https://picsum.photos/seed/drama27/400/600",
    description: "On her wedding day, she discovers her groom murdered her father. The honeymoon becomes a battlefield.",
    categories: ["Suspense","Revenge"],
    actors: ["Vera Steel","Ash Knight"],
    rating: 8.8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 54,
    createdAt: "2024-03-27",
  },
  {
    _id: "28",
    title: "My CEO Neighbor",
    cover: "https://picsum.photos/seed/drama28/400/600",
    description: "She thought her annoying neighbor was a jobless slacker — until she saw him on the cover of Forbes.",
    categories: ["CEO","Comedy","Romance"],
    actors: ["Daisy Bright","Rex Gold"],
    rating: 8.1,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 42,
    createdAt: "2024-04-28",
  },
  {
    _id: "29",
    title: "Pack Wars",
    cover: "https://picsum.photos/seed/drama29/400/600",
    description: "When the Blood Moon rises, three wolf packs must fight for dominance — and only one alpha will survive.",
    categories: ["Werewolf","Fantasy","Suspense"],
    actors: ["Freya Wild","Thor Pack"],
    rating: 8.7,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 76,
    createdAt: "2024-05-01",
  },
  {
    _id: "30",
    title: "The Heiress Returns",
    cover: "https://picsum.photos/seed/drama30/400/600",
    description: "Thrown out as a child, she returns as the richest woman in the country to face the family that abandoned her.",
    categories: ["Revenge","CEO","Drama"],
    actors: ["Elena Crown","Victor King"],
    rating: 9,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 70,
    createdAt: "2024-06-02",
  },
  {
    _id: "31",
    title: "Cursed Love",
    cover: "https://picsum.photos/seed/drama31/400/600",
    description: "Every person she falls in love with dies within a year. Can the curse be broken before it claims him too?",
    categories: ["Fantasy","Romance"],
    actors: ["Hazel Spell","Finn Curse"],
    rating: 8.5,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 60,
    createdAt: "2024-07-03",
  },
  {
    _id: "32",
    title: "Office Wars",
    cover: "https://picsum.photos/seed/drama32/400/600",
    description: "Two department heads wage an epic office war — with pranks, sabotage, and undeniable chemistry.",
    categories: ["CEO","Comedy"],
    actors: ["Penny Sharp","Gil Smooth"],
    rating: 8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 36,
    createdAt: "2024-08-04",
  },
  {
    _id: "33",
    title: "The Vampire's Bride",
    cover: "https://picsum.photos/seed/drama33/400/600",
    description: "Sold to a vampire lord to pay her family's debt, she discovers he's not the monster everyone fears.",
    categories: ["Fantasy","Romance"],
    actors: ["Scarlet Fang","Drake Blood"],
    rating: 8.8,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 74,
    createdAt: "2024-09-05",
  },
  {
    _id: "34",
    title: "Revenge Wears Prada",
    cover: "https://picsum.photos/seed/drama34/400/600",
    description: "A fashion intern discovers her boss destroyed her mother's career. Now she'll dismantle the empire stitch by stitch.",
    categories: ["Revenge","Urban","Drama"],
    actors: ["Olive Silk","Hugo Stitch"],
    rating: 8.6,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 58,
    createdAt: "2024-10-06",
  },
  {
    _id: "35",
    title: "Fated to the Alpha",
    cover: "https://picsum.photos/seed/drama35/400/600",
    description: "She's an omega — the weakest of her kind. But fate has paired her with the most powerful alpha alive.",
    categories: ["Werewolf","Romance"],
    actors: ["Willow Howl","Blaze Alpha"],
    rating: 8.9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 80,
    createdAt: "2024-11-07",
  },
  {
    _id: "36",
    title: "The Cold CEO's Warm Heart",
    cover: "https://picsum.photos/seed/drama36/400/600",
    description: "Everyone says CEO Jiang has no heart. His new assistant is about to prove them all wrong.",
    categories: ["CEO","Romance"],
    actors: ["Pearl Ice","Stone Heart"],
    rating: 8.3,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 50,
    createdAt: "2024-12-08",
  },
  {
    _id: "37",
    title: "Demon's Contract",
    cover: "https://picsum.photos/seed/drama37/400/600",
    description: "She made a deal with a demon to save her sister. The price? Seven years of servitude — and her soul.",
    categories: ["Fantasy","Suspense"],
    actors: ["Raven Dark","Lucian Fire"],
    rating: 8.7,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 68,
    createdAt: "2024-01-09",
  },
  {
    _id: "38",
    title: "Second Chance at Love",
    cover: "https://picsum.photos/seed/drama38/400/600",
    description: "Divorced and broken, she runs into her college sweetheart — who never stopped loving her.",
    categories: ["Romance","Drama"],
    actors: ["Hope Spring","Grant Fall"],
    rating: 8.2,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 44,
    createdAt: "2024-02-10",
  },
  {
    _id: "39",
    title: "The Luna's Revenge",
    cover: "https://picsum.photos/seed/drama39/400/600",
    description: "Betrayed by her pack and left for dead, the former Luna rises with a new pack and an unstoppable thirst for justice.",
    categories: ["Werewolf","Revenge"],
    actors: ["Sierra Moon","Fenris Claw"],
    rating: 9.1,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 86,
    createdAt: "2024-03-11",
  },
  {
    _id: "40",
    title: "Married to the Mafia Boss",
    cover: "https://picsum.photos/seed/drama40/400/600",
    description: "To protect her family, she agrees to marry the city's most dangerous man — and discovers his darkest secret.",
    categories: ["Suspense","Romance"],
    actors: ["Jade Danger","Marco Don"],
    rating: 8.5,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 62,
    createdAt: "2024-04-12",
  },
  {
    _id: "41",
    title: "The Enchantress",
    cover: "https://picsum.photos/seed/drama41/400/600",
    description: "Born with the power to control emotions, she's feared by all — until a man immune to her magic appears.",
    categories: ["Fantasy","Romance"],
    actors: ["Crystal Charm","Orion Spell"],
    rating: 8.8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 72,
    createdAt: "2024-05-13",
  },
  {
    _id: "42",
    title: "CEO's Fake Fiancée",
    cover: "https://picsum.photos/seed/drama42/400/600",
    description: "He needs a fake fiancée for his grandmother's birthday. She needs rent money. What could go wrong?",
    categories: ["CEO","Romance","Comedy"],
    actors: ["Poppy Sweet","Beau Fake"],
    rating: 8.1,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 46,
    createdAt: "2024-06-14",
  },
  {
    _id: "43",
    title: "Blood Moon Pack",
    cover: "https://picsum.photos/seed/drama43/400/600",
    description: "The rarest wolf — a white alpha — emerges during the Blood Moon, and every pack wants to claim her.",
    categories: ["Werewolf","Fantasy"],
    actors: ["Dawn White","Silas Grey"],
    rating: 8.6,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 78,
    createdAt: "2024-07-15",
  },
  {
    _id: "44",
    title: "Empire of Lies",
    cover: "https://picsum.photos/seed/drama44/400/600",
    description: "Behind the glamorous facade of the Chen empire lies murder, betrayal, and a daughter who knows the truth.",
    categories: ["Revenge","CEO","Suspense"],
    actors: ["Carmen Truth","Nero Lie"],
    rating: 9.2,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 92,
    createdAt: "2024-08-16",
  },
  {
    _id: "45",
    title: "Starlight Romance",
    cover: "https://picsum.photos/seed/drama45/400/600",
    description: "A struggling actress and a famous director clash on set — and spark a romance that captivates the nation.",
    categories: ["Romance","Urban"],
    actors: ["Stella Light","Ray Shine"],
    rating: 8,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 40,
    createdAt: "2024-09-17",
  },
  {
    _id: "46",
    title: "The Lycan Prince",
    cover: "https://picsum.photos/seed/drama46/400/600",
    description: "The last Lycan prince has been in hiding for centuries. When his mate finally appears, war follows.",
    categories: ["Werewolf","Fantasy","Romance"],
    actors: ["Lyra Fang","Ronan Prince"],
    rating: 9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 84,
    createdAt: "2024-10-18",
  },
  {
    _id: "47",
    title: "Shattered Crown",
    cover: "https://picsum.photos/seed/drama47/400/600",
    description: "A dethroned empress plots her return to power in a court filled with poison, politics, and passion.",
    categories: ["Revenge","Historical"],
    actors: ["Mei Jade","Shen Gold"],
    rating: 8.7,
    episodes: [],
    isCompleted: true,
    year: 2024,
    totalEpisodes: 66,
    createdAt: "2024-11-19",
  },
  {
    _id: "48",
    title: "Love in Disguise",
    cover: "https://picsum.photos/seed/drama48/400/600",
    description: "To escape an arranged marriage, she disguises herself as a man — and accidentally becomes her crush's roommate.",
    categories: ["Romance","Comedy"],
    actors: ["Rosie Laugh","Kit Smile"],
    rating: 8.2,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 42,
    createdAt: "2024-12-20",
  },
  {
    _id: "49",
    title: "The Omega's Rise",
    cover: "https://picsum.photos/seed/drama49/400/600",
    description: "Born the weakest omega, she defies every expectation and rises to become the first female alpha in wolf history.",
    categories: ["Werewolf","Romance","Drama"],
    actors: ["Athena Rise","Titan Fall"],
    rating: 8.8,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 76,
    createdAt: "2024-01-21",
  },
  {
    _id: "50",
    title: "Midnight Heir",
    cover: "https://picsum.photos/seed/drama50/400/600",
    description: "At midnight on her 21st birthday, she inherits powers that make her the target of every supernatural faction in the city.",
    categories: ["Fantasy","Suspense","Romance"],
    actors: ["Nova Midnight","Caspian Heir"],
    rating: 8.9,
    episodes: [],
    isCompleted: false,
    year: 2024,
    totalEpisodes: 70,
    createdAt: "2024-02-22",
  }
];

export const mockCategories: Category[] = [
  { _id: "1", name: "Romance", slug: "romance" },
  { _id: "2", name: "Revenge", slug: "revenge" },
  { _id: "3", name: "CEO", slug: "ceo" },
  { _id: "4", name: "Werewolf", slug: "werewolf" },
  { _id: "5", name: "Suspense", slug: "suspense" },
  { _id: "6", name: "Fantasy", slug: "fantasy" },
  { _id: "7", name: "Urban", slug: "urban" },
  { _id: "8", name: "Drama", slug: "drama" },
  { _id: "9", name: "Comedy", slug: "comedy" },
  { _id: "10", name: "Historical", slug: "historical" },
  { _id: "11", name: "Mystery", slug: "mystery" },
];
