import type { Drama, Category } from "@/types";

// Mock data for development
export const mockDramas: Drama[] = [
  {
    id: "1",
    title: "The CEO's Secret Love",
    cover: "https://picsum.photos/seed/drama1/400/600",
    description: "A romantic story about a CEO and his secret love.",
    categories: ["Romance", "Drama"],
    actors: ["John Doe", "Jane Smith"],
    rating: 4.5,
    episodes: [
      { id: "e1", dramaId: "1", title: "Episode 1", episodeNumber: 1, videoUrl: "", thumbnail: "", duration: 1800, isFree: true, unlockPrice: 0 },
      { id: "e2", dramaId: "1", title: "Episode 2", episodeNumber: 2, videoUrl: "", thumbnail: "", duration: 1800, isFree: true, unlockPrice: 0 },
      { id: "e3", dramaId: "1", title: "Episode 3", episodeNumber: 3, videoUrl: "", thumbnail: "", duration: 1800, isFree: true, unlockPrice: 0 },
      { id: "e4", dramaId: "1", title: "Episode 4", episodeNumber: 4, videoUrl: "", thumbnail: "", duration: 1800, isFree: false, unlockPrice: 100 },
    ],
    isCompleted: false,
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    title: "Revenge of the Princess",
    cover: "https://picsum.photos/seed/drama2/400/600",
    description: "A princess seeks revenge on those who wronged her family.",
    categories: ["Historical", "Drama"],
    actors: ["Alice Wang", "Bob Chen"],
    rating: 4.8,
    episodes: [],
    isCompleted: true,
    createdAt: "2024-02-01",
  },
  {
    id: "3",
    title: "Sweet Love in Office",
    cover: "https://picsum.photos/seed/drama3/400/600",
    description: "A romantic comedy set in a modern office.",
    categories: ["Romance", "Comedy"],
    actors: ["Carol Zhang", "David Li"],
    rating: 4.3,
    episodes: [],
    isCompleted: false,
    createdAt: "2024-03-01",
  },
  {
    id: "4",
    title: "Mysterious Doctor",
    cover: "https://picsum.photos/seed/drama4/400/600",
    description: "A doctor with a mysterious past.",
    categories: ["Mystery", "Romance"],
    actors: ["Eve Liu", "Frank Wu"],
    rating: 4.6,
    episodes: [],
    isCompleted: false,
    createdAt: "2024-04-01",
  },
  {
    id: "5",
    title: "Powerful CEO",
    cover: "https://picsum.photos/seed/drama5/400/600",
    description: "The rise of a powerful CEO.",
    categories: ["Business", "Drama"],
    actors: ["Grace Yang", "Henry Zhou"],
    rating: 4.4,
    episodes: [],
    isCompleted: true,
    createdAt: "2024-05-01",
  },
  {
    id: "6",
    title: "Love in the City",
    cover: "https://picsum.photos/seed/drama6/400/600",
    description: "Love stories in a big city.",
    categories: ["Romance", "Urban"],
    actors: ["Ivy Chen", "Jack Ma"],
    rating: 4.2,
    episodes: [],
    isCompleted: false,
    createdAt: "2024-06-01",
  },
];

export const mockCategories: Category[] = [
  { id: "1", name: "Romance", slug: "romance" },
  { id: "2", name: "Drama", slug: "drama" },
  { id: "3", name: "Comedy", slug: "comedy" },
  { id: "4", name: "Historical", slug: "historical" },
  { id: "5", name: "Mystery", slug: "mystery" },
  { id: "6", name: "Business", slug: "business" },
];
