'use client';

import { useState, useRef, useCallback, useEffect } from 'react';
import * as tus from 'tus-js-client';

interface VideoUploaderProps {
  onUploadComplete: (videoUid: string) => void;
  onFileSelected?: (file: { name: string; size: number }) => void;
  onProgress?: (percent: number) => void;
  onError?: (error: string) => void;
  className?: string;
}

type UploadState = 'idle' | 'uploading' | 'success' | 'error';

interface ValidationResult {
  valid: boolean;
  error?: string;
  suggestion?: string;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:7002';

// Validation constants
const MAX_FILE_SIZE = 5 * 1024 * 1024 * 1024; // 5GB in bytes
const ALLOWED_MIME_TYPE = 'video/mp4';
const ALLOWED_EXTENSION = '.mp4';

export default function VideoUploader({
  onUploadComplete,
  onFileSelected,
  onProgress,
  onError,
  className = '',
}: VideoUploaderProps) {
  const [state, setState] = useState<UploadState>('idle');
  const [progress, setProgress] = useState(0);
  const [dragOver, setDragOver] = useState(false);
  const [fileName, setFileName] = useState('');
  const [fileSize, setFileSize] = useState(0);
  const [errorMsg, setErrorMsg] = useState('');
  const [errorSuggestion, setErrorSuggestion] = useState('');

  const inputRef = useRef<HTMLInputElement>(null);
  const uploadRef = useRef<tus.Upload | null>(null);
  // mockTimerRef removed — no more fake progress simulation

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (uploadRef.current) {
        uploadRef.current.abort();
      }
    };
  }, []);

  // Warn user before leaving during upload
  useEffect(() => {
    if (state === 'uploading') {
      const handler = (e: BeforeUnloadEvent) => {
        e.preventDefault();
        e.returnValue = '';
      };
      window.addEventListener('beforeunload', handler);
      return () => window.removeEventListener('beforeunload', handler);
    }
  }, [state]);

  const formatSize = (bytes: number) => {
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  };

  // Generate auto filename
  const generateAutoFilename = (): string => {
    const timestamp = new Date().toISOString().replace(/[-:T.Z]/g, '').slice(0, 14);
    const random = Math.random().toString(16).slice(2, 8);
    return `video_${timestamp}_${random}.mp4`;
  };

  const validateFile = (file: File): ValidationResult => {
    // 1. Check file size (5GB limit)
    if (file.size > MAX_FILE_SIZE) {
      const sizeGB = (file.size / (1024 * 1024 * 1024)).toFixed(2);
      return {
        valid: false,
        error: `视频文件过大（${sizeGB}GB），最大支持 5GB`,
        suggestion: '建议：使用 HandBrake 或 FFmpeg 压缩视频，或将视频分割为多个片段'
      };
    }

    // 2. Check MIME type
    if (file.type !== ALLOWED_MIME_TYPE) {
      return {
        valid: false,
        error: `仅支持 MP4 格式视频，当前文件格式：${file.type || '未知'}`,
        suggestion: '建议：使用 HandBrake、FFmpeg 或在线转换工具将视频转换为 MP4 格式'
      };
    }

    // 3. Check file extension
    const ext = file.name.toLowerCase().slice(file.name.lastIndexOf('.'));
    if (ext !== ALLOWED_EXTENSION) {
      return {
        valid: false,
        error: `文件扩展名必须为 .mp4，当前扩展名：${ext}`,
        suggestion: '建议：检查文件扩展名，或使用视频转换工具重新导出为 MP4 格式'
      };
    }

    return { valid: true };
  };

  const handleUpload = useCallback(async (file: File) => {
    const validation = validateFile(file);
    if (!validation.valid) {
      setErrorMsg(validation.error || '文件验证失败');
      setErrorSuggestion(validation.suggestion || '');
      setState('error');
      onError?.(validation.error || '文件验证失败');
      return;
    }

    // Generate auto filename
    const autoGeneratedName = generateAutoFilename();

    setFileName(file.name);
    setFileSize(file.size);
    setState('uploading');
    setProgress(0);
    setErrorMsg('');
    setErrorSuggestion('');
    onFileSelected?.({ name: file.name, size: file.size });

    try {
      // Request TUS upload URL from backend
      const token = typeof window !== 'undefined' ? localStorage.getItem('admin_token') : null;
      const res = await fetch(`${API_BASE}/api/admin/upload/video`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          filename: file.name,
          filesize: file.size,
          mimetype: file.type,
          autoGeneratedName
        }),
      });

      if (!res.ok) {
        const errBody = await res.json().catch(() => ({}));
        throw new Error(errBody?.error?.message || `Upload service error (${res.status})`);
      }

      const { data } = await res.json();
      const { upload_url, video_uid } = data;

      // Start TUS upload — use uploadUrl (not endpoint) for Cloudflare direct creator uploads
      const upload = new tus.Upload(file, {
        uploadUrl: upload_url,
        chunkSize: 20 * 1024 * 1024,
        retryDelays: [0, 1000, 3000, 5000, 10000],
        metadata: {
          filename: file.name,
          filetype: file.type,
        },
        onProgress: (bytesUploaded, bytesTotal) => {
          const pct = Math.round((bytesUploaded / bytesTotal) * 100);
          setProgress(pct);
          onProgress?.(pct);
        },
        onSuccess: () => {
          setProgress(100);
          setState('success');
          onUploadComplete(video_uid);
        },
        onError: (err) => {
          const msg = err.message || 'Upload failed';
          setErrorMsg(msg);
          setState('error');
          onError?.(msg);
        },
      });

      uploadRef.current = upload;
      upload.start();
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to connect to upload service. Please check your network and try again.';
      setErrorMsg(msg);
      setState('error');
      onError?.(msg);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [onUploadComplete, onProgress, onError]);

  const handleCancel = () => {
    if (uploadRef.current) {
      uploadRef.current.abort();
      uploadRef.current = null;
    }
    setState('idle');
    setProgress(0);
    setFileName('');
    setFileSize(0);
    setErrorMsg('');
  };

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    if (file) handleUpload(file);
  }, [handleUpload]);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
  }, []);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) handleUpload(file);
    if (inputRef.current) inputRef.current.value = '';
  };

  const reset = () => {
    setState('idle');
    setProgress(0);
    setFileName('');
    setFileSize(0);
    setErrorMsg('');
    setErrorSuggestion('');
  };

  return (
    <div className={`w-full ${className}`}>
      <input
        ref={inputRef}
        type="file"
        accept="video/mp4,.mp4"
        onChange={handleFileSelect}
        className="hidden"
      />

      {/* Idle State: Drop Zone */}
      {state === 'idle' && (
        <div
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onClick={() => inputRef.current?.click()}
          className={`flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed px-6 py-12 transition-colors ${
            dragOver
              ? 'border-amber-400 bg-amber-400/10'
              : 'border-white/20 bg-zinc-900 hover:border-white/40 hover:bg-zinc-800/50'
          }`}
        >
          <svg className="mb-3 h-10 w-10 text-zinc-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
          </svg>
          <p className="text-sm font-medium text-zinc-300">
            Click to upload or drag video here
          </p>
          <p className="mt-1 text-xs text-zinc-500">
            Max 5GB &middot; MP4 only
          </p>
        </div>
      )}

      {/* Uploading State */}
      {state === 'uploading' && (
        <div className="rounded-xl border border-white/10 bg-zinc-900 p-5">
          <div className="mb-3 flex items-center justify-between">
            <div className="min-w-0 flex-1">
              <p className="truncate text-sm font-medium text-zinc-200">{fileName}</p>
              <p className="text-xs text-zinc-500">{formatSize(fileSize)}</p>
            </div>
            <button
              onClick={handleCancel}
              className="ml-3 rounded-lg p-1.5 text-zinc-500 transition-colors hover:bg-zinc-800 hover:text-zinc-300"
              aria-label="Cancel upload"
            >
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div className="h-2 w-full overflow-hidden rounded-full bg-zinc-800">
            <div
              className="h-full rounded-full bg-gradient-to-r from-amber-500 to-yellow-400 transition-all duration-300"
              style={{ width: `${progress}%` }}
            />
          </div>
          <p className="mt-2 text-right text-xs font-medium text-amber-400">{progress}%</p>
        </div>
      )}

      {/* Success State */}
      {state === 'success' && (
        <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-5">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-500/20">
              <svg className="h-4 w-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
              </svg>
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-medium text-emerald-300">Upload complete</p>
              <p className="truncate text-xs text-zinc-400">{fileName}</p>
            </div>
            <button
              onClick={reset}
              className="rounded-lg px-3 py-1.5 text-xs font-medium text-zinc-400 transition-colors hover:bg-zinc-800 hover:text-zinc-200"
            >
              Upload another
            </button>
          </div>
        </div>
      )}

      {/* Error State */}
      {state === 'error' && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-5">
          <div className="flex items-start gap-3">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-500/20">
              <svg className="h-4 w-4 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
              </svg>
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-semibold text-red-300">上传失败</p>
              <p className="mt-1 text-sm text-gray-300">{errorMsg}</p>
              {errorSuggestion && (
                <p className="mt-2 text-xs text-gray-400">{errorSuggestion}</p>
              )}
            </div>
          </div>
          <button
            onClick={reset}
            className="mt-4 w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-indigo-700"
          >
            我知道了
          </button>
        </div>
      )}
    </div>
  );
}